### ISSUE TITLE
NES.StringWay

### ISSUE THREAD

**Issue by volak** [elliotritchie/NES#33]
Is your intention with this new namespace to make a NES that allows both Guid and string ids?  
I am still playing with the v5 branch version and happen to need aggregates with string ids for a specific root.

The implementation looks like that is what you are aiming for, but IRepositoryAdd still only accepts an AggregateBase with a Guid id so its kind of useless for adding.

I am attempting to fix it up but need to know what your intentions for the namespace are

Thanks

**Comment by marinkobabic** [comment]
The implementation has been simplified.
