### ISSUE TITLE
Documentation / Tutorial

### ISSUE THREAD

**Issue by roy-t** [elliotritchie/NES#36]
I believe the documentation of this project is extremely sparse (sorry, I know its not the fun part of a project ;) ). I'm not able to fully understand the code, even though the underlying concepts are slightly familiar (took some CQRS/event sourcing) work shops. Especially the sample is a bit of a mystery since it doesn't seem to use NEventStore but a XmlDocument for storage, (isn't the whole idea of NES to use NEventStore?). I'm also having trouble understanding from the sample why so much code needs to be duplicated (the create commands and events seem to do almost the same). 

Now this all is probably due to a gap in knowledge, but without at least something resembling a tutorial I'm afraid I can't get much further (in a time efficient manner that is ;) ).

Is there any more documentation, or better: a tutorial, for the NES project? Or are there other resources that I should read first (maybe some NEventStore and NServiceBus manuals that I should read first, though the NEventStore documentation doesn't seem to be much more comprehensive :( ). So that its easier to get into NES? Or maybe NES isn't the right CQRS/Event Sourcing framework to start off with? I'm open to suggestions?

**Comment by marinkobabic** [comment]
The framework is just a technical implementation of the CQRS. DDD is the part the people should focus on. So in this case I would suggest this book https://vaughnvernon.co/?page_id=168

If you look in the real word the command contains clear instructions what you should do. When the job is done you will write down all the things you have done and report it using the event. Between the command and report there will not be a huge gap, in the normal case. The event is the part which will be persisted into eventstore. In the NES example the denormilizer takes the reported event and persists the data into the database or in this sample into xml to use it as readmodel. 

So we have here all parts you learned. Command, Domain, Eventstore, Denormilizer and Readmodel. You just need to identify them in the sample.

**Comment by roy-t** [comment]
I understand (I've read Vernon's book). I think it would help if the sample actually used NEventStore, since wiring NEventStore with NEventBus is what this project is for ;). I'll see if I can get everything to work now (have slept on it, that always helps). Maybe I can contribute to the sample?

**Comment by marinkobabic** [comment]
You are right. You can make a pull request :-) Thanks

**Comment by elliotritchie** [comment]
The NES sample uses NServiceBus and NEventStore, it's what NES is for after all. Basically:

1. Website sends a command.
2. Endpoint handles the command.
3. Aggregate creates an event.
4. Event is persisted to the event store.
5. Endpoint publishes the event.
6. Endpoint handles the event.
7. Dto is persisted to XML file.

There's a few [Q&As](http://stackoverflow.com/questions/9153807/cqrs-nes-insight-into-how-sample-project-works) on stackoverflow that might be useful.

I hope this helps.

**Comment by roy-t** [comment]
@elliotritchie 

I've cloned the samples, and there isn't even a reference to NEventStore in it. So I'm still pretty sure its not using NEventStore ;). However, the Q&A you mentioned and the overview of order of events/commands is helpful :).

@marinkobabic cool, I'll see what I can do. Got a busy work week ahead so it might take some time.

**Comment by elliotritchie** [comment]
https://github.com/elliotritchie/NES/blob/master/samples/NES.Sample/EndpointConfig.cs#L24-L28

**Comment by roy-t** [comment]
@elliotritchie 

It seems I'm having a bad day

No NEventStore: https://github.com/elliotritchie/NES/tree/master/samples/packages

NEventStore: https://github.com/elliotritchie/NES/blob/master/samples/NES.Sample/packages.config

:/ apologies.
