### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by mojamcpds** [elliotritchie/NES#37]
private static readonly ILogger Logger = LoggerFactory.Create(typeof(EventHandlerFactory)); return null reference exception.

**I have written my code as follows:**

` private static readonly IEventFactory _eventFactory = DI.Current.Resolve<IEventFactory>();
        private static readonly IEventHandlerFactory _eventHandlerFactory = DI.Current.Resolve<IEventHandlerFactory>();
        private readonly string nameOrConnectionString;
        private readonly RetryPolicy<SqlAzureTransientErrorDetectionStrategy> retryPolicy;

        public ConferenceService(string nameOrConnectionString = "ConferenceManagement")
        {
           
            this.nameOrConnectionString = nameOrConnectionString;

            this.retryPolicy = new RetryPolicy<SqlAzureTransientErrorDetectionStrategy>(new Incremental(5, TimeSpan.FromSeconds(0), TimeSpan.FromSeconds(1.5)) { FastFirstRetry = true });
            this.retryPolicy.Retrying += (s, e) =>
                Trace.TraceWarning("An error occurred in attempt number {1} to access the database in ConferenceService: {0}", e.LastException.Message, e.CurrentRetryCount);
 
        }

        public void CreateConference(ConferenceInfo conference)
        {
            using (var context = new ConferenceContext(this.nameOrConnectionString))
            {
                var existingSlug = this.retryPolicy.ExecuteAction(() => 
                    context.Conferences
                        .Where(c => c.Slug == conference.Slug)
                        .Select(c => c.Slug)
                        .Any());

                if (existingSlug)
                    throw new DuplicateNameException("The chosen conference slug is already taken.");

                // Conference publishing is explicit. 
                if (conference.IsPublished)
                    conference.IsPublished = false;

                context.Conferences.Add(conference);
                this.retryPolicy.ExecuteAction(() => context.SaveChanges());

               this.PublishConferenceEvent<ConferenceCreated>(conference);
            }
        }

private void PublishConferenceEvent<T>(ConferenceInfo conference)
            where T : ConferenceEvent, new()
        {

            Action<T> action = x => new T
            {
                SourceId = conference.Id,
                Owner = new Owner
                {
                    Name = conference.OwnerName,
                    Email = conference.OwnerEmail,
                },
                Name = conference.Name,
                Description = conference.Description,
                Location = conference.Location,
                Slug = conference.Slug,
                Tagline = conference.Tagline,
                TwitterSearch = conference.TwitterSearch,
                StartDate = conference.StartDate,
                EndDate = conference.EndDate,
            };

            Apply(action);
        }

       protected void Apply<TEvent>(Action<TEvent> action)
        {
           var @event = _eventFactory.Create(action);
           Raise(@event);
        }

        private void Raise(object @event)
        {
            _eventHandlerFactory.Get(this, @event.GetType())(@event);
        }
`

**When I run the application and trying to create a conference it returns following error message**

> Object reference not set to an instance of an object.
> 
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
> 
> Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
> 
> Source Error: 
> 
> 
> Line 10:     public class EventHandlerFactory : IEventHandlerFactory
> Line 11:     {
> Line 12:         private static readonly ILogger Logger = LoggerFactory.Create(typeof(EventHandlerFactory));
> Line 13:         private static readonly Dictionary<Type, Dictionary<Type, Action<object, object>>> _cache = new Dictionary<Type, Dictionary<Type, Action<object, object>>>();
> Line 14:         private static readonly object _cacheLock = new object();
> 
> Source File: F:\MyProjects\NES\NES-master\src\NES\EventHandlerFactory.cs    Line: 12 
> 
> Stack Trace: 
> 
> 
> [NullReferenceException: Object reference not set to an instance of an object.]
>    NES.EventHandlerFactory..cctor() in F:\MyProjects\NES\NES-master\src\NES\EventHandlerFactory.cs:12
> 
> [TypeInitializationException: The type initializer for 'NES.EventHandlerFactory' threw an exception.]
>    NES.EventHandlerFactory..ctor() +0
>    NES.<>c.<.cctor>b__4_4() in F:\MyProjects\NES\NES-master\src\NES\DI.cs:24
>    NES.DependencyInjectionContainer.Resolve() in F:\MyProjects\NES\NES-master\src\NES\DependencyInjectionContainer.cs:21
>    Conference.ConferenceService..cctor() in F:\MyProjects\NES\NES-master\samples\Conference\ConferenceService.cs:23
> 
> [TypeInitializationException: The type initializer for 'Conference.ConferenceService' threw an exception.]
>    Conference.ConferenceService..ctor(String nameOrConnectionString) in F:\MyProjects\NES\NES-master\samples\Conference\ConferenceService.cs:36
>    Conference.Web.Admin.Controllers.ConferenceController.get_Service() in F:\MyProjects\NES\NES-master\samples\Conference.Web.Admin\Controllers\ConferenceController.cs:32
>    Conference.Web.Admin.Controllers.ConferenceController.Create(ConferenceInfo conference) in F:\MyProjects\NES\NES-master\samples\Conference.Web.Admin\Controllers\ConferenceController.cs:119
>    lambda_method(Closure , ControllerBase , Object[] ) +180
>    System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters) +68
>    System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +486
>    System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +71
>    System.Web.Mvc.Async.ActionInvocation.InvokeSynchronousActionMethod() +85
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +44
>    System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +82
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +143
>    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +109
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +58
>    System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +121
>    System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +321
>    System.Web.Mvc.Async.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) +53
>    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +56
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +143
>    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +109
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +58
>    System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +76
>    System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +184
>    System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +53
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +140
>    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +63
>    System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +50
>    System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +45
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +81
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +140
>    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +63
>    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +47
>    System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +50
>    System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +50
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +140
>    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +63
>    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +47
>    System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +50
>    System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +50
>    System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +45
>    System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +81
>    System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +140
>    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +63
>    System.Web.Mvc.Async.AsyncResultWrapper.End(IAsyncResult asyncResult, Object tag) +47
>    System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +50
>    System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +49
>    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9644037
>    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by marinkobabic** [comment]
It seems like the LoggerFactory.Create action is not set. NServiceBus normally calls the following class https://github.com/elliotritchie/NES/blob/c83ec59a43dcd310e4b1a5ea5a53aeb89cd64948/src/NES.NServiceBus/ConfigurationRunner.cs

The question is at the point you face the problem is the NServiceBus running?

**Comment by marinkobabic** [comment]
If the problem still persists then you should ensure that nservicebus also scans the NES dll like described in the readme.

**Comment by mojamcpds** [comment]
Thanks. Fixed the issue. The problem was in my configuration.

**Comment by mojamcpds** [comment]
In NES.CQRS sample I didn't found any code regarding register Events with EventHandlers. Can anybody tell me where this has been done?

**Comment by marinkobabic** [comment]
This is done by NServiceBus. During the startup you can watch the mapping in the log.

**Comment by mojamcpds** [comment]
Can I have any details tutorial of NES.CQRS framework. I really love this framework and work deeply with it.

**Comment by marinkobabic** [comment]
You said that you use unity as dependency injection container. But not for the **RegistrationEndPoint.Backend** so next to the NServiceBus.Host.exe you can find the log file nsb_log_2016-02-27_0.txt and here some content of the file

Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Registration.Handlers.OrderCommandHandler' can be invoked with the available services and parameters:
Cannot resolve parameter 'Registration.IPricingService pricingService' of constructor 'Void .ctor(NES.Contracts.IRepository, Registration.IPricingService)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorTypeChecker.cs:line 0
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorTypeChecker.cs:line 0

NServiceBus uses Autofac and it has no idea about your dependencies. So you should use unity like you do it in your Conference.Web.Public project.

**Comment by mojamcpds** [comment]
Then shall I also have to resolve same dependencies (Those I already resolved inside Conference.Web.Public) inside RegistrationEndPoint.Backend

**Comment by marinkobabic** [comment]
You have to register the same dependencies like you did in Conference.Web.Public and use unity. The resolve we added just for testing purposes. The resolve code is not needed in production.
